/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'UsersUpdate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UsersResetPassword': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UsersGetById': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UsersGetAll': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UsersDelete': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UsersCreate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UnitsUpdate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UnitsGetById': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UnitsGetAll': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UnitsDelete': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UnitsCreate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DesignationsUpdate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DesignationsGetById': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DesignationsGetAll': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DesignationsDelete': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DesignationsCreate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AuthRefresh': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AuthGetCurrentUser': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AuthLogout': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AuthLogin': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AuthChangePassword': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
}