/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'UsersUpdate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UsersUpdatePreferences': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UsersResetPassword': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UsersGetPreferences': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UsersGetById': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UsersGetAll': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UsersDelete': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UsersCreate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UserTagsUpdate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UserTagsGet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UserEffectiveScope': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UnitsUpdate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UnitsGetById': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UnitsGetAll': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UnitsDelete': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UnitsCreate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UnitTagsUpdate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UnitTagsGet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'TagsUpdate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'TagsToggle': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'TagsList': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'TagsCreate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DesignationsUpdate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DesignationsGetById': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DesignationsGetAll': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DesignationsDelete': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DesignationsCreate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DesignationPermissionsUpdate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DesignationPermissionsGet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ConfigGetByKey': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ConfigGetAll': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsSubmissionsStats': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsSubmissionsList': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsSubmissionsGet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsSubmissionsCreate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsQuestionsUsage': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsQuestionsUpdate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsQuestionsToggleStatus': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsQuestionsList': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsQuestionsGet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsQuestionsDelete': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsQuestionsCreate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsMetrics': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsFormsUpdate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsFormsToggleStatus': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsFormsStats': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsFormsList': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsFormsGet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsFormsDuplicate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsFormsDelete': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsFormsCreate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsFormAccess': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsFindingsUpdate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsFindingsStats': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsFindingsList': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsFindingsGet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsFindingsDelete': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsFindingsCreate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsFindingsAllowedValues': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsConfigFindingsValuesPut': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsConfigFindingsValuesGet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CheckOpsConfigAllowedValues': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AuthRefresh': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AuthGetCurrentUser': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AuthLogout': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AuthLogin': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AuthChangePassword': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
}